"""Add emergency contacts table

Revision ID: c2e52c76851b
Revises: 1af8428a0339
Create Date: 2025-11-28 04:11:30.074998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e52c76851b'
down_revision = '1af8428a0339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_contacts')
    # ### end Alembic commands ###
